# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

User:
  fields:
    default: login, email, login_count, failed_login_count, last_request_at, current_login_at, last_login_at, current_login_ip, last_login_ip
    form: login, email, login_count, failed_login_count, last_request_at, current_login_at, last_login_at, current_login_ip, last_login_ip
  order_by: 
  relationships: 
  filters: created_at
  search: 
  application: wedding

